[semver:patch] TSR-1298 | Improve error handling for image signing
* Bump only to 455

Signed-off-by: Hoang Quoc Trung <trung.hoang@pricehubble.com>

* Retry with ServiceUsage API enabled

Signed-off-by: Hoang Quoc Trung <trung.hoang@pricehubble.com>

* Add missing project id

Signed-off-by: Hoang Quoc Trung <trung.hoang@pricehubble.com>

* Improve digest fetching

Signed-off-by: Hoang Quoc Trung <trung.hoang@pricehubble.com>

* Print digests for testing

Signed-off-by: Hoang Quoc Trung <trung.hoang@pricehubble.com>

* Use exact tag for image digest fetching

Signed-off-by: Hoang Quoc Trung <trung.hoang@pricehubble.com>

* Test with gcloud artifacts docker images list instead

Signed-off-by: Hoang Quoc Trung <trung.hoang@pricehubble.com>

* Add echo for debugging

Signed-off-by: Hoang Quoc Trung <trung.hoang@pricehubble.com>

* I'm dumb

Signed-off-by: Hoang Quoc Trung <trung.hoang@pricehubble.com>

* [skip ci] Update changelog

Signed-off-by: Hoang Quoc Trung <trung.hoang@pricehubble.com>


Approved-by: Michele Pittoni

diff --git a/src/commands/bump.yml b/src/commands/bump.yml
--- a/src/commands/bump.yml
+++ b/src/commands/bump.yml
@@ -119,7 +119,12 @@ steps:
           export IMAGE_TAG="${CIRCLE_WORKFLOW_ID}.${CIRCLE_SHA1}"
         
           if [[ "<< parameters.use-digest >>" = "true" ]]; then
-            export IMAGE_DIGEST=$(gcloud artifacts docker images describe --format='value(image_summary.digest)' "${IMAGE_FULL_PATH}:${IMAGE_TAG}")
+            export IMAGE_DIGEST=$(gcloud artifacts docker images list "${IMAGE_FULL_PATH}" --format='value(version)' --include-tags --quiet --filter="tags:(${IMAGE_TAG})")
+            echo $IMAGE_DIGEST
+            if [ $? -ne 0 ]; then
+              echo "Failed to translate image tag ${IMAGE_TAG} to sha256..."
+              exit 1
+            fi
           fi
         else
           export IMAGE_TAG="<< parameters.tag >>"
