[semver:patch] Merged in alpha (pull request #26)
Fix orb integration tests after secrets cleanup

* Fix always location

Signed-off-by: Trung <trung.hoang@pricehubble.com>

* Merge branch 'main' into alpha

* TSR-413 Add retry on bump push step

Insert a retry of up to 5 attempts with a random sleep

* TSR-413 Update CHANGELOG

* Merged in TSR-413/bump-retry (pull request #25)

TSR-413 Add retry on bump push step

Approved-by: Trung Hoang
* Fix orb integration tests after secrets cleanup

Signed-off-by: Trung <trung.hoang@pricehubble.com>

* Remove extraneous token removal

Signed-off-by: Trung <trung.hoang@pricehubble.com>

* Update changelog

Signed-off-by: Trung <trung.hoang@pricehubble.com>

* Update changelog

Signed-off-by: Trung <trung.hoang@pricehubble.com>

* Update changelog

Signed-off-by: Trung <trung.hoang@pricehubble.com>


Approved-by: Michele Pittoni

diff --git a/src/commands/bump.yml b/src/commands/bump.yml
--- a/src/commands/bump.yml
+++ b/src/commands/bump.yml
@@ -162,12 +162,29 @@ steps:
           command: |
             cd << parameters.releaser-repo >>
 
-            # git pull here ensures that no changes occurred in between the initial pull and the push
-            # git push --force-with-lease refuses to update a remote ref that is not an ancestor of the local ref used to overwrite it
-            # which a second safety mechanism to avoid unintentionally overwriting changes
-            #
-            # NOTE: git push exits 0 even if no changes occurred
-            git pull --rebase && \
-              git push --force-with-lease --set-upstream origin << parameters.releaser-branch >>
+            # retry pushing up to 5 times, with a random sleep (1-6 seconds) in between
+            n=0
+            until [ "$n" -ge 5 ]; do
+
+              # git pull here ensures that no changes occurred in between the initial pull and the push
+              # git push --force-with-lease refuses to update a remote ref that is not an ancestor of the local ref used to overwrite it
+              # which a second safety mechanism to avoid unintentionally overwriting changes
+              #
+              # NOTE: git push exits 0 even if no changes occurred
+              git pull --rebase && \
+                git push --force-with-lease --set-upstream origin << parameters.releaser-branch >> && \
+                break # exit the retry loop if successful
+
+              echo "Push attempt number $n failed"
+              n=$(($n+1))
+              sleep $((1 + $RANDOM % 5))
+            done
 
             cd -
+
+  - run:
+      name: Clean up ssh keys
+      when: always
+      command: |
+        shred -f -u \
+          ~/.ssh/id_releaser || :
